name: "Load buildkit state from cache"
description: "Copies state from cache into specified buildkit builder"
inputs:
  builder:
    description: "buildkit builder to use"
  cache-path:
    description: "path to restored cache file"
  cache-max-size:
    description: "maximum cache size"

runs:
  using: "node16"
  main: "main.js"
  post: "post.js"
